// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zdmjwyzchjriezxnjppg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpkbWp3eXpjaGpyaWV6eG5qcHBnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxOTQ0OTcsImV4cCI6MjA3MDc3MDQ5N30.wGTGm4S8xp-8lXMLr5d0uLrkaxtCI2kgLE2qv7kjYbU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});